version: '3.4'

networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 162.16.0.0/16

volumes:
  myweb: 
    
services:
  web:
    image: mahendrshinde/myweb
    ports:
      - 9000:80
    volumes:
      - myweb:/usr/share/nginx/logs