version: '3.4'

networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 162.16.0.0/16
    
services:
  lb:
    image: mahendrshinde/nginx-lb:1
    networks:
    - mynet
    environment:
      app_srv: web
      app_port: 80

    ports:
    - 9000:80

  web:
    image: mahendrshinde/myweb
    deploy:
      replicas: 3
    networks:
    - mynet
    